### PR TITLE
Added some haikus for WindowsError

### PR DESCRIPTION
**Pull request by jotes**
Hi @swistakm, could you review?

### CODE REVIEW

**Comment by swistakm** [comment]
Thanks for PR! There is one issue to fix: `WindowsError` is available only on windows. We could wrap this in `try: ... except NameError: pass` block.

**Comment by jotes** [comment]
@swistakm  You're totally right, but I wasn't sure if it would be a bug or a feature ;-) Fixed, could you look again?

**Comment by swistakm** [comment]
I fully understand ;-) Thanks for contribution. You're great!

**Comment by swistakm** [comment]
released as [0.1.0](https://github.com/pylola/haiku-errors/releases/tag/0.1.0) and new version is already available on [PyPI](https://pypi.python.org/pypi/haiku-errors)

**Pull request merged**
